site_name: Lab Books
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - search.highlight
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md
  - Projects:
      - Project 1: projects/project-1.md
      - Project 2: projects/project-2.md
      - Project 3: projects/project-3.md